Repository daengnyang-market/daengnyang-market-client, pull requests merged in 2022-12, with the labels that each got.

#4 edit: 프로필 정보 수정
  README.md
Labels: docs

#16 design: 전역 스타일 수정 및 추가 (#15)
  src/styles/GlobalStyle.jsx
  src/styles/global.css
Labels: design

#18 design: 공통UI 파트2 화면개발(#9)
  src/App.jsx
  src/components/common/Comment/Comment.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/components/common/TopNavBar/Styled.jsx
  src/components/common/TopNavBar/TopBasicNav.jsx
  src/components/common/TopNavBar/TopChatNav.jsx
  src/components/common/TopNavBar/TopMainNav.jsx
  src/components/common/TopNavBar/TopSearchNav.jsx
  src/components/common/TopNavBar/TopUploadNav.jsx
Labels: design

#20 design: 공통UI 파트4 버튼 화면개발 (#11)
  src/components/common/Button/Button.jsx
Labels: design

#19 design: 공통UI 파트1 화면개발 (#12)
  src/components/common/Post/Post.jsx
  src/components/common/Product/Product.jsx
Labels: design

#17 design: 공통UI 파트3 화면개발 (#10)
  src/components/common/Alert/Alert.jsx
  src/components/common/Animation/Animation.jsx
  src/components/common/HiddenMenu/HiddenMenu.jsx
  src/components/common/Input/Input.jsx
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/userItem/Follow/Follow.jsx
  src/components/common/userItem/Search/Search.jsx
  src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
Labels: design

#28 design: 공통UI 파트2 화면개발 버튼 및 프로필 이미지 컴포넌트 추가 (#21)
  src/components/common/Comment/Comment.jsx
  src/components/common/TopNavBar/TopUploadNav.jsx
Labels: design

#31 design: 공통UI 파트1 화면개발 ProfileImage 컴포넌트 추가 (#26)
  src/components/common/Post/Post.jsx
Labels: design

#33 design: Input.jsx 속 InputWrapper 스타일 수정 (#32)
  src/components/common/Input/Input.jsx
Labels: design

#40 design: 버튼 사이즈별 width를 고정값으로 수정 (#36)
  src/components/common/Button/Button.jsx
Labels: design

#42 design: 버튼 사이즈가 L 일 때의 스타일 변경 (#41)
  src/components/common/Button/Button.jsx
Labels: design

#34 design: 시작 화면 퍼블리싱 완료 (#29)
  src/pages/SplashScreen/SplashScreen.jsx
Labels: design

#43 design: 이메일 로그인 화면 퍼블리싱 (#30)
  src/pages/EmailLoginPage/EmailLoginPage.jsx
Labels: design

#50 design: Input.jsx 스타일 추가 (#48)
  src/components/common/Input/Input.jsx
Labels: design

#52 design: 회원가입 메인화면 구성 (#27)
  src/pages/JoinMembershipPage/JoinMembershipPage.jsx
Labels: design

#45 design: App.jsx 파일 내 스크린 스타일 추가 (#44)
  src/App.jsx
  src/components/common/TabMenu/TabMenu.jsx
  src/components/common/TopNavBar/Styled.jsx
Labels: design

#56 design: ContentsLayout 컴포넌트 추가 (#47)
  src/components/layout/ContentsLayout/ContentsLayout.jsx
Labels: design

#63 design: TopMainNav, TopTitleNav의 title을 props로 받도록 변경 (#59)
  src/components/common/TopNavBar/TopMainNav.jsx
  src/components/common/TopNavBar/TopTitleNav.jsx
Labels: design

#58 design: Button.jsx 파일 스타일 변경 (#57)
  src/components/common/Button/Button.jsx
Labels: design

#67 design: 피드 페이지 퍼블리싱 (#38)
  src/pages/FeedPage/FeedPage.jsx
Labels: design

#73 style: Button 커스텀을 위한 props 및 클릭핸들러 추가 (#72)
  src/components/common/Button/Button.jsx
Labels: design

#76 design: 팔로우 목록 페이지 퍼블리싱 (#46)
  src/pages/FollowListPage/FollowListPage.jsx
Labels: design

#75 design: Search 메인화면 퍼블리싱 (#65)
  src/components/common/TopNavBar/Styled.jsx
  src/components/common/TopNavBar/TopSearchNav.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: design

#77 design: Follow 컴포넌트 버튼 토글 기능 추가 (#74)
  src/components/common/userItem/Follow/Follow.jsx
Labels: design

#81 [design] 이메일 로그인 페이지 내 로그인 버튼에 disabled 옵션 추가 (#80)
  src/pages/EmailLoginPage/EmailLoginPage.jsx
Labels: design

#87 assets: 커뮤니티 페이지 캐러셀 구현을 위한 이미지 에셋 추가 (#85)
  src/assets/images/advertising1-image.png
  src/assets/images/advertising2-image.png
  src/assets/images/advertising3-image.png
  src/styles/CommonImages.jsx
Labels: assets

#89 design: 게시물 상세 페이지 퍼블리싱 (#78)
  src/components/common/Comment/Comment.jsx
  src/pages/PostDetailPage/PostComment.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
Labels: design

#92 design: Pagination Carousel 컴포넌트 구현 (#91)
  src/components/carousel/PaginationCarousel/PaginationCarousel.jsx
Labels: design

#94 design: 커뮤니티(집사생활) 메인 페이지 퍼블리싱 (#79)
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
  src/pages/communityPage/CommunityMainPage/PopularPosts.jsx
  src/pages/communityPage/CommunityMenu.jsx
Labels: design

#101 design: ProfileImage 컴포넌트 스타일 커스텀 기능 추가 (#93)
  src/components/common/ProfileImage/ProfileImage.jsx
Labels: design

#103 design: MultiItemCarousel 캐러셀 컴포넌트 구현 (#102)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
  src/components/carousel/MultiItemCarousel/multiItemCarousel.css
Labels: design

#106 design: PostUploadPage 퍼블리싱 (#96)
  src/pages/PostUploadPage/PostUploadDetail.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
Labels: design

#111 design: NotFoundLocation 컴포넌트 구현 (#110)
  src/pages/communityPage/NotFoundLocation.jsx
Labels: design

#109 design: 커뮤니티 날씨 페이지 퍼블리싱 (#95)
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/CommunityWeatherPage/DetailWeatherInfo.jsx
  src/pages/communityPage/CommunityWeatherPage/SummaryWeatherInfo.jsx
Labels: design

#113 design: YourProfilePage 페이지 퍼블리싱(#64)
  src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
  src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
  src/pages/yourProfilePage/YourHeader/YourHeader.jsx
  src/pages/yourProfilePage/YourPost/YourPost.jsx
  src/pages/yourProfilePage/YourProduct/YourProduct.jsx
  src/pages/yourProfilePage/YourProfilePage.jsx
Labels: design

#121 assets: 커뮤니티 동물병원 페이지 구현을 위한 아이콘 에셋 추가 (#118)
  src/assets/icons/animal-hospital-icon.png
  src/assets/icons/bottom-arrow-icon.png
  src/assets/icons/location-black-icon.png
  src/assets/icons/location-icon.png
  src/assets/icons/right-arrow-icon.png
  src/styles/CommonIcons.jsx
Labels: assets

#122 design: 리스트 아이템을 받아 HiddenMenu를 구성할 수 있도록 컴포넌트 확장 (#120)
  src/components/common/HiddenMenu/HiddenMenu.jsx
Labels: design

#129 fix: TopNavBar style z-index 버그 수정 (#127)
  src/components/common/TopNavBar/Styled.jsx
Labels: bug fix

#128 design: TopNavBar 커스텀 (#126)
  src/components/common/TopNavBar/TopMainNav.jsx
  src/components/common/TopNavBar/TopTitleNav.jsx
Labels: design

#130 design: 커뮤니티 페이지 TopNav, CommunityMenu 디자인 시안에 맞춰 수정 (#125)
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
  src/pages/communityPage/CommunityMenu.jsx
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/CommunityHospitalDetailPage.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitaMainlPage.jsx
Labels: design

#141 design: 댓글에 모달 연결 (#138)
  src/components/common/modal/CommentModal/CommentModal.jsx
  src/pages/PostDetailPage/PostComment.jsx
Labels: design

#142 design: 게시글에 모달 연결 (#137)
  src/components/common/Post/Post.jsx
  src/components/common/modal/PostModal/PostModal.jsx
Labels: design

#143 design: 판매 중인 상품에 모달 연결 (#136)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
  src/components/common/Product/Product.jsx
Labels: design

#147 design: 선택한 페이지에 따라 TabMenu 스타일 변경 (#146)
  src/components/common/TabMenu/TabMenu.jsx
Labels: design

#149 feat: 업로드한 이미지 미리보기 기능 추가 (#148)
  src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
Labels: feat

#153 design: App.jsx 내부 레이아웃 분리 (#151)
  src/components/layout/ContentsLayout/FrameLayout.jsx
  src/components/layout/ContentsLayout/MainLayout.jsx
Labels: design

#159 feat: TabMenu에 페이지 연결 (#158)
  src/components/common/TabMenu/TabMenu.jsx
  src/pages/FollowListPage/FollowListPage.jsx
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/routes/Router.jsx
Labels: feat

#164 feat: TopNavBar 뒤로가기 및 search 페이지로 이동 기능 추가 (#163)
  src/components/common/TopNavBar/TopBasicNav.jsx
  src/components/common/TopNavBar/TopMainNav.jsx
  src/components/common/TopNavBar/TopSearchNav.jsx
  src/components/common/TopNavBar/TopTitleNav.jsx
  src/components/common/TopNavBar/TopUploadNav.jsx
Labels: feat

#162 feat: ProfilePage에 모달 연결 (#135)
  src/components/common/TopNavBar/TopBasicNav.jsx
  src/components/common/modal/ProfileModal/ProfileModal.jsx
  src/pages/profilePage/ProfilePage.jsx
Labels: feat

#117 design: 채팅 페이지 퍼블리싱 (#108)
  src/pages/ChatRoomPage/ChatRoomPage.jsx
  src/pages/ChatRoomPage/ChatUploadComment.jsx
  src/pages/ChatRoomPage/MyChat.jsx
  src/pages/ChatRoomPage/UserChat.jsx
Labels: design

#167 style: 채팅방 리스트 퍼블리싱 (#155)
  src/pages/chatListPage/ChatList.jsx
  src/pages/chatListPage/ChatListPage.jsx
  src/routes/Router.jsx
Labels: design

#165 feat: 채팅방에 모달 연결 (#140)
  src/components/common/TopNavBar/TopBasicNav.jsx
  src/components/common/TopNavBar/TopTitleNav.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/routes/Router.jsx
Labels: feat

#172 design: 상품 수정 페이지 퍼블리싱 (#107)
  src/pages/ProductModificationPage/ProductModificationPage.jsx
Labels: design

#177 feat: TabMenu 채팅 메뉴와 채팅 목록 페이지 연결 (#176)
  src/pages/chatListPage/ChatList.jsx
  src/pages/chatListPage/ChatListPage.jsx
Labels: feat

#201 refactor: Button.jsx 스타일에서 여러번 props 받아오는것 수정 (#198)
  src/components/common/Button/Button.jsx
  src/pages/JoinMembershipPage/JoinMembershipPage.jsx
  src/routes/Router.jsx
Labels: cleanup

#182 feat: 회원가입 기능 구현 및 유효성 검사 (#178)
  src/pages/JoinMembershipPage/JoinMembershipInput.jsx
  src/pages/JoinMembershipPage/JoinMembershipPage.jsx
  src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
  src/routes/Router.jsx
Labels: feat

#195 feat: 로그인 기능 구현 (#166, #197)
  .eslintrc.json
  src/App.jsx
  src/context/AuthContext.jsx
  src/hooks/.gitkeep
  src/hooks/useInput.jsx
  src/pages/EmailLoginPage/EmailLoginInput.jsx
  src/pages/EmailLoginPage/EmailLoginPage.jsx
Labels: feat

#212 fix: token 값이 localStorage에 저장되어 있는데도 null로 인식되는 버그 (#211)
  src/context/AuthContext.jsx
Labels: bug fix

#215 fix: 토큰 없을 때 예외처리 추가 및 렌더링 에러 해결 (#213, #214)
  src/pages/SplashScreen/SplashScreen.jsx
Labels: bug fix

#218 fix: 최초 로그인 후 FeedPage로 이동했을 때 401 에러 발생 현상 (#214 이슈 재오픈)
  src/context/AuthContext.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/SplashScreen/SplashScreen.jsx
Labels: bug fix

#219 feat: 로그아웃 기능 구현 (#208)
  src/components/common/modal/ProfileModal/ProfileModal.jsx
Labels: feat

#204 design: 인풋 대거 수정으로 인한, 스타일 누락된 부분 수정 (#203)
  src/pages/JoinMembershipPage/JoinMembershipInput.jsx
Labels: design

#223 fix: 최초 로그인 시 피드 게시물을 가져오지 못하는 현상 수정을 위해 토큰 로직 변경 (#221)
  src/App.jsx
  src/components/common/modal/ProfileModal/ProfileModal.jsx
  src/context/AuthContext.jsx
  src/pages/EmailLoginPage/EmailLoginPage.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/SplashScreen/SplashScreen.jsx
Labels: feat

#226 feat: 상품 등록 페이지 기능 구현 (#200)
  src/pages/ProductRegistrationPage/ItemLinkInput.jsx
  src/pages/ProductRegistrationPage/ItemNameInput.jsx
  src/pages/ProductRegistrationPage/PriceInput.jsx
  src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
Labels: feat

#228 feat: AuthContext에 로그인한 사용자의 accountname 저장 (#227)
  src/components/common/modal/ProfileModal/ProfileModal.jsx
  src/context/AuthContext.jsx
  src/pages/EmailLoginPage/EmailLoginPage.jsx
Labels: feat

#233 feat: 검색 기능 추가 (#205)
  src/components/common/ProfileImage/ProfileImage.jsx
  src/components/common/userItem/Search/Search.jsx
  src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
  src/pages/SearchPage/SearchPage.jsx
Labels: feat

#243 feat: 팔로우 리스트 조회 및 팔로우/팔로우 취소 기능 구현 (#220)
  src/components/common/userItem/Follow/Follow.jsx
  src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
  src/pages/FollowListPage/EmptyFollowList.jsx
  src/pages/FollowListPage/FollowListPage.jsx
Labels: feat

#247 feat: Post 컴포넌트에 서버 데이터 출력 (#246)
  src/components/common/Post/Post.jsx
  src/pages/FeedPage/FeedPage.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: feat

#250 feat: 프로필 설정 페이지 추가적인 기능 구현 (#248)
  src/pages/ProfileSettingsPage/InputAccountName.jsx
  src/pages/ProfileSettingsPage/InputIntro.jsx
  src/pages/ProfileSettingsPage/InputUserDescription.jsx
  src/pages/ProfileSettingsPage/ProfileInfo.jsx
  src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
Labels: feat

#249 feat: 커뮤니티 메인 페이지 실시간 인기글 기능 구현 (#244)
  src/assets/images/advertising3-image.png
  src/assets/images/advertising4-image.png
  src/components/carousel/PaginationCarousel/PaginationCarousel.jsx
  src/components/carousel/PaginationCarousel/paginationCarousel.css
  src/pages/FeedPage/FeedPage.jsx
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
  src/pages/communityPage/CommunityMainPage/EmptyPosts.jsx
  src/pages/communityPage/CommunityMainPage/PopularPosts.jsx
  src/styles/CommonImages.jsx
Labels: feat

#254 feat: 게시물 업로드 기능 구현 (#245)
  src/pages/PostUploadPage/ImageUploadButton.jsx
  src/pages/PostUploadPage/PostUploadDetail.jsx
  src/pages/PostUploadPage/PostUploadPage.jsx
Labels: feat

#255 feat: 프로필 수정 페이지 기능 구현 (#253)
  src/pages/ProfileModificationPage/ProfileModificationPage.jsx
  src/pages/ProfileSettingsPage/InputAccountName.jsx
  src/pages/ProfileSettingsPage/InputIntro.jsx
  src/pages/ProfileSettingsPage/InputUserName.jsx
  src/pages/ProfileSettingsPage/ProfileInfo.jsx
  src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
Labels: feat

#259 feat: 현재 위치를 기준으로 행정구, 날씨, 미세먼지 정보를 가져오는 기능 구현 (#251)
  .gitignore
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/CommunityWeatherPage/DetailWeatherInfo.jsx
  src/pages/communityPage/CommunityWeatherPage/DustBadgeStyled.jsx
  src/pages/communityPage/CommunityWeatherPage/SummaryWeatherInfo.jsx
  src/utils/WeatherDescription.jsx
Labels: feat

#267 fix: 회원가입 시 이미지 미적용에 따른 기본 프로필 이미지로 대체되는 현상 수정 (#266)
  src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
Labels: bug fix

#273 feat: 날씨 페이지 내 기본 위치 설정 및 현재 위치 업데이트 기능 추가. 사용자 경험 개선 위함 (#271)
  src/assets/icons/update-icon.png
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/CommunityWeatherPage/SummaryWeatherInfo.jsx
  src/styles/CommonIcons.jsx
Labels: feat

#277 fix: 프로필 이미지가 꽉 차지 않는 현상 해결을 위해 object-fit: cover로 변경 (#276)
  src/components/common/ProfileImage/ProfileImage.jsx
Labels: bug fix

#278 feat: 산책 난이도 책정 기능 추가 (#260)
  src/assets/images/walking-easy-image.png
  src/assets/images/walking-hard-image.png
  src/assets/images/walking-normal-image.png
  src/pages/ChatRoomPage/MyChat.jsx
  src/pages/ChatRoomPage/UserChat.jsx
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/CommunityWeatherPage/DetailWeatherInfo.jsx
  src/pages/communityPage/CommunityWeatherPage/SummaryWeatherInfo.jsx
  src/styles/CommonImages.jsx
  src/utils/WeatherDescription.jsx
Labels: feat

#286 fix: 판매중인 상품의 이미지 찌그러짐 현상 해결 (#285)
  src/components/carousel/MultiItemCarousel/multiItemCarousel.css
  src/components/common/Product/Product.jsx
  src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
  src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
Labels: design, bug fix

#283 feat: 상품 수정 페이지 및 ProductModal 컴포넌트 내 수정 기능 구현 (#262)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
  src/components/common/TopNavBar/TopUploadNav.jsx
  src/components/common/modal/ProductModal/ProductModal.jsx
  src/pages/ProductModificationPage/ProductModificationPage.jsx
  src/pages/ProductRegistrationPage/ItemLinkInput.jsx
  src/pages/ProductRegistrationPage/ItemNameInput.jsx
  src/pages/ProductRegistrationPage/PriceInput.jsx
  src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
  src/routes/Router.jsx
Labels: feat

#264 feat: 게시물 화면 구현 및 댓글 기능 추가 (#258)
  src/components/common/Comment/Comment.jsx
  src/pages/PostDetailPage/DetailPost.jsx
  src/pages/PostDetailPage/PostComment.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
Labels: feat

#290 feat: 다른사용자의 상품 클릭했을때 판매사이트로 이동하는 기능 추가 (#289)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
  src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
  src/pages/profilePage/ProfilePage.jsx
Labels: design, feat

#297 feat: 현재 위치를 기준으로 가까운 동물병원 목록을 가져오는 기능 추가 (#279)
  src/App.jsx
  src/assets/icons/update-white-icon.png
  src/context/UserLocationContext.jsx
  src/hooks/useLocation.jsx
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
  src/pages/communityPage/CommunityMenu.jsx
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/CommunityWeatherPage/SummaryWeatherInfo.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitaMainlPage.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/HospitalList.jsx
  src/pages/communityPage/communityHospitalPage/CurrentLocationBar.jsx
  src/styles/CommonIcons.jsx
Labels: feat, api

#299 feat: props로 closeAlert을 전달받지 않은 경우 closeAlert 버튼이 출력되지 않도록 수정 (#298)
  src/components/common/modal/Alert.jsx
Labels: feat

#303 fix: useLocation 커스텀 훅을 useCurrentLocation으로 변경 (#302)
  src/hooks/useCurrentLocation.jsx
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitaMainlPage.jsx
Labels: bug fix

#301 feat: ProductModal 기능 추가 (#296)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
  src/components/common/modal/ProductModal/ProductModal.jsx
  src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
Labels: feat

#307 fix: default image 수정 (#291)
  src/pages/ProfileSettingsPage/DefaultImage.jsx
  src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
Labels: bug fix

#306 feat: PostModal 삭제/신고 기능 구현
  src/components/common/Post/Post.jsx
  src/components/common/modal/PostModal/PostModal.jsx
Labels: feat

#293 fix: 게시물 클릭했을때, 임의로 설정해둔 postid 값의 게시물로만 이동하는 오류 수정 (#292)
  src/pages/PostDetailPage/PostDetailPage.jsx
Labels: bug fix

#317 fix: 이미지 두개이상 존재할시, 이미지 렌더 안되는 문제 및 캐러셀 작동 추가 구현 (#313)
  src/components/common/Post/Post.jsx
  src/components/common/modal/PostModal/PostModal.jsx
  src/pages/PostDetailPage/DetailPost.jsx
  src/pages/PostDetailPage/PostDetailPage.jsx
  src/pages/PostUploadPage/ImageUploadButton.jsx
  src/pages/PostUploadPage/PostUploadDetail.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: bug fix

#308 feat: 프로필페이지 채팅 이동 및 카카오톡 공유하기 기능 추가 (#294)
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
Labels: feat, api

#314 feat: 상품 가격 표시 기능 개선 (#310)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
Labels: feat

#321 fix: 게시물과 모달 작업시 발생한 자잘한 버그 수정 (#320)
  src/components/common/Post/Post.jsx
  src/components/common/modal/PostModal/PostModal.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
  src/routes/Router.jsx
Labels: bug fix

#322 fix: 게시물 수정시 생기는 버그 (#319)
  src/components/common/Post/Post.jsx
  src/components/common/modal/PostModal/PostModal.jsx
  src/pages/PostUploadPage/ImageUploadButton.jsx
  src/pages/PostUploadPage/PostUploadDetail.jsx
Labels: bug fix

#325 fix: 숫자만 입력받을 수 있도록 수정 (#309)
  src/pages/ProductRegistrationPage/PriceInput.jsx
Labels: bug fix

#330 fix: ProductProfile useEffect 배열에서 productList 요소 삭제 (#329)
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
  src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
Labels: bug fix

#326 refactor: ProfilePost 앨범형,리스트형 코드 리팩토링 (#324)
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: design, feat, cleanup

#327 feat: 댓글 삭제 및 신고기능 추가 (#323)
  src/components/common/modal/CommentModal/CommentModal.jsx
  src/pages/PostDetailPage/PostComment.jsx
Labels: feat

#339 fix: 게시물 이미지 파일이 존재하지 않을때도 빈 이미지 파일이 렌더되는 현상 수정 (#338)
  src/components/common/Post/Post.jsx
Labels: bug fix

#340 refactor: 가격 입력 시 콤마로 표시 하기 기능 추가 (#328)
  src/pages/ProductRegistrationPage/PriceInput.jsx
Labels: refactor

#336 feat: 동물병원 상세정보 페이지 기능 구현 및 디자인 수정 (#300)
  package-lock.json
  package.json
  public/index.html
  src/assets/icons/location-black-icon.png
  src/assets/icons/location-border-icon.png
  src/assets/icons/phone-icon.png
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/CommunityHospitalDetailPage.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/HospitalDetail.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/HospitalMap.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalDetailPage/KakaoShareButton.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/CommunityHospitalMainPage.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/HospitalItem.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalMainPage/HospitalList.jsx
  src/pages/communityPage/communityHospitalPage/CommunityHospitalPage.jsx
  src/pages/communityPage/communityHospitalPage/CurrentLocationBar.jsx
  src/routes/Router.jsx
  src/styles/CommonIcons.jsx
Labels: design, feat, api

#343 refactor: 프로필페이지,상품,게시글 로딩컴포넌트 추가 (#342)
  src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
  src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
Labels: refactor

#347 fix: 노드환경에서 발생하는 Warning 해결 (#345)
  src/components/common/Post/Post.jsx
  src/pages/PostDetailPage/PostComment.jsx
  src/pages/profilePage/ProfilePage.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: bug fix

#353 fix: Post 댓글버튼 클릭시 상세페이지로 이동하게 수정 (#350)
  src/components/common/Post/Post.jsx
  src/pages/PostDetailPage/PostComment.jsx
Labels: bug fix

#355 fix: 라우터 접근제한 기능 추가 (#252)
  src/routes/AuthRoute.jsx
  src/routes/NonAuthRoute.jsx
  src/routes/Router.jsx
Labels: feat, bug fix

#357 feat: 이메일로 회원가입 페이지로 이동 기능 추가 (#356)
  src/pages/EmailLoginPage/EmailLoginPage.jsx
Labels: bug fix

#360 design: 버튼 컴포넌트에 isActive 옵션 추가 (#358)
  src/components/common/Button/Button.jsx
  src/components/common/userItem/Follow/Follow.jsx
Labels: design, bug fix

#362 refactor: 이미지 리사이징을 위한 코드 추가 및 이미지 스타일 속성 변경을 위한 코드 수정 (#352)
  src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
Labels: refactor

#364 fix: 상품명 길이 제한 수정 (#363)
  src/pages/ProductRegistrationPage/ItemNameInput.jsx
Labels: bug fix

#372 fix: 판매 링크 입력 시 주소를 복사해서 넣으면 생기는 버그 수정 (#365)
  src/pages/ProductModificationPage/ProductModificationPage.jsx
  src/pages/ProductRegistrationPage/ItemLinkInput.jsx
  src/pages/ProductRegistrationPage/ProductRegistrationPage.jsx
Labels: bug fix

#371 feat: 채팅 기능 추가 (#348)
  src/pages/ChatRoomPage/ChatRoomPage.jsx
  src/pages/ChatRoomPage/ChatUploadComment.jsx
  src/pages/ChatRoomPage/MyChat.jsx
  src/pages/ChatRoomPage/UserChat.jsx
  src/pages/chatListPage/ChatList.jsx
  src/pages/chatListPage/ChatListPage.jsx
  src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
  src/pages/profilePage/ProfilePage.jsx
Labels: feat

#377 fix: 앨범형 게시글 클릭 시 포스트 디테일로 이동하게 수정 (#374)
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: feat, bug fix

#376 fix: 초기 채팅리스트 랜더오류,서버채팅 토큰 미설정 오류 및 시간미설정 (#375)
  src/pages/ChatRoomPage/MyChat.jsx
  src/pages/ChatRoomPage/UserChat.jsx
  src/pages/chatListPage/ChatList.jsx
  src/pages/chatListPage/ChatListPage.jsx
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
Labels: bug fix

#381 fix: 대화 역순으로 나열되는 버그 수정 (#380)
  src/pages/ChatRoomPage/ChatRoomPage.jsx
  src/pages/chatListPage/ChatList.jsx
Labels: bug fix

#379 style: 프로필 소개글 양쪽 여백 스타일 추가 (#378)
  src/pages/profilePage/ProfileHeader/ProfileHeader.jsx
Labels: design, bug fix

#359 feat: react-intersection-observer 라이브러리로 피드 페이지 무한스크롤 기능 추가 (#354)
  package-lock.json
  package.json
  src/components/common/Post/Post.jsx
  src/pages/FeedPage/FeedPage.jsx
Labels: feat, assets

#382 fix: 기존 계정 ID로 입력 시 발생하는 오류 수정 및 불필요한 코드 삭제 (#261)
  src/pages/ProfileModificationPage/ProfileModificationPage.jsx
  src/pages/ProfileSettingsPage/InputAccountName.jsx
  src/pages/ProfileSettingsPage/ProfileInfo.jsx
Labels: bug fix

#385 feat: 커뮤니티 메인 페이지 무한 스크롤 구현 및 추천글 정렬 기준 변경 (#369, #370)
  src/pages/communityPage/CommunityMainPage/CommunityMainPage.jsx
  src/pages/communityPage/CommunityMainPage/PopularPosts.jsx
Labels: feat, bug fix

#388 fix: 피드 페이지 코드 누락으로 게시물이 없을 때 공간이 남아 보이는 현상 (#387)
  src/pages/profilePage/ProfilePage.jsx
Labels: bug fix

#389 fix: 상품 삭제시 새로고침 이벤트 추가 (#366)
  src/components/common/modal/ProductModal/ProductModal.jsx
Labels: bug fix

#392 refactor: 이미지 리사이징을 위한 코드 추가 (#384)
  src/pages/ProfileSettingsPage/ProfileInfo.jsx
Labels: refactor

#396 fix: 타 유저 프로필에서 채팅기능 클릭했을시, 채팅방이 존재하면 알림창이 안뜨는 버그 수정 (#395)
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
Labels: bug fix

#401 fix: 프로필 수정시 바로 업데이트 되지 않는 버그 해결 (#398)
  src/components/common/Button/Button.jsx
  src/components/common/TopNavBar/TopUploadNav.jsx
  src/pages/ProfileModificationPage/ProfileModificationPage.jsx
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
Labels: bug fix

#400 feat: 카카오톡 프로필 공유시 이미지 추가 및 소개글 수정 (#399)
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
Labels: feat

#403 refactor: 판매 중인 상품 삭제 시 발생하는 렌더링에 대한 리팩토링 (#402)
  src/components/carousel/MultiItemCarousel/MultiItemCarousel.jsx
  src/components/common/modal/ProductModal/ProductModal.jsx
  src/pages/profilePage/ProfileProduct/ProfileProduct.jsx
Labels: refactor

#394 style: ProfileProduct 캐러셀 높이값 조정 (#391)
  src/components/carousel/MultiItemCarousel/multiItemCarousel.css
Labels: design
