Repository daengnyang-market/daengnyang-market-client, pull requests merged in 2023-01, with the labels that each got.

#411 feat: 게시물 좋아요기능 구현 (#410)
  src/components/LikeBtn/LikeBtn.jsx
  src/components/common/Post/Post.jsx
Labels: feat, api

#405 fix/feat: 동물병원 근처 동물병원이 최대 15개만 보이는 버그 수정 및 필터 유지 기능 추가 (#386, #404)
  src/components/common/TopNavBar/TopTitleNav.jsx
  src/hooks/useCurrentLocation.jsx
  src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/CommunityHospitalMainPage.jsx
  src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/FilterMenu.jsx
  src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/HospitalList.jsx
  src/pages/communityPage/CommunityLayout.jsx
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
Labels: feat, bug fix

#409 fix: 오래된 채팅도 확인하여, 채팅룸이 존재하면 채팅생성 방지하도록 수정 (#408)
  src/pages/profilePage/ProfileHeader/UserProfileBtns.jsx
Labels: bug fix

#407 fix: 프로필 계정 ID 수정 시 프로필 페이지 오류 현상 개선 (#383)
  src/pages/ProfileModificationPage/ProfileModificationPage.jsx
  src/pages/profilePage/ProfilePage.jsx
Labels: bug fix

#406 fix: 프로필 포스트 10개만 받아와지는 현상 무한스크롤 구현으로 해결 (#397)
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: feat, bug fix

#414 feat: 위치 정보 에러시 / 동물병원 상세정보 페이지 URL이 잘못된 경우 예외처리 구현 (#281, #418)
  src/context/UserLocationContext.jsx
  src/hooks/useCurrentLocation.jsx
  src/pages/communityPage/CommunityHospitalPage/CommunityHospitalDetailPage/CommunityHospitalDetailPage.jsx
  src/pages/communityPage/CommunityHospitalPage/CommunityHospitalMainPage/CommunityHospitalMainPage.jsx
  src/pages/communityPage/CommunityMenu.jsx
  src/pages/communityPage/CommunityWeatherPage/CommunityWeatherPage.jsx
  src/pages/communityPage/NotFound.jsx
  src/pages/communityPage/NotFoundLocation.jsx
Labels: feat, bug fix

#415 fix: URL 경로에 따라 상이한 Favicon (#181)
  public/favicon/favicon-32x32.png
  public/favicon/favicon.ico
  public/index.html
Labels: bug fix

#417 fix: UserAccountInfo 내부 내용이 길어질 경우 넘치는 현상 (#416)
  src/components/common/userItem/UserAccountInfo/UserAccountInfo.jsx
Labels: design, bug fix

#422 refactor: Enter 이벤트를 위한 코드 추가 및 불필요한 코드 삭제 (#419)
  src/pages/ProfileSettingsPage/ProfileInfo.jsx
  src/pages/ProfileSettingsPage/ProfileSettingsPage.jsx
Labels: refactor

#425 fix: 캐러셀 높이값 수정 및 하단과의 간격 추가 (#423)
  src/components/common/Post/Post.jsx
Labels: design, bug fix

#427 refactor: 프로필 소개, 계정 ID에 대한 프로필 세팅 페이지 리팩토링 (#426)
  src/pages/ProfileSettingsPage/InputAccountName.jsx
  src/pages/ProfileSettingsPage/ProfileInfo.jsx
Labels: refactor

#428 fix: 게시물 글이 길 경우 화면 밖으로 빠져나가는 현상 word-break 속성 추가로 해결 (#424)
  src/components/common/Post/Post.jsx
Labels: design, bug fix

#432 refactor: 사용하지 않는 ref 삭제 및 전개 구문을 이용한 코드 간략화 (#431)
  src/pages/EmailLoginPage/EmailLoginInput.jsx
  src/pages/EmailLoginPage/EmailLoginPage.jsx
Labels: refactor

#430 fix: 무한스크롤 기능 추가시 가장 마지막 게시글 보이지 않는 현상 수정 (#429)
  src/pages/FeedPage/FeedPage.jsx
  src/pages/profilePage/ProfilePost/ProfilePost.jsx
Labels: bug fix

#433 fix: 프로필 주소 변경시 프로필 포스트들이 재렌더링 되지 않는 현상 해결 (#421)
  src/pages/profilePage/ProfilePage.jsx
Labels: bug fix

#435 fix: 게시물 업로드 및 수정시, 이미지 3장이상 업로드 불가하도록 수정 (#434)
  src/pages/PostUploadPage/ImageUploadButton.jsx
Labels: bug fix

#437 feat: 채팅방 나가기 기능 추가 (#420)
  src/components/common/modal/ChatRoomModal/ChatRoomModal.jsx
  src/pages/chatListPage/ChatListPage.jsx
Labels: feat

#439 fix: 게시물 작성 시, 3장 이상 이미지를 업로드 할 때 alert 창은 뜨지만 업로드할 이미지는 계속 추가되는 현상 (#438)
  src/pages/PostUploadPage/ImageUploadButton.jsx
  src/pages/PostUploadPage/PostUploadDetail.jsx
Labels: bug fix

#443 fix: ChatListPage key 중복 경고 해결 (#442)
  src/pages/ChatListPage/ChatListPage.jsx
Labels: bug fix

#448 cleanup: 담당했던 기능 파일 변수명을 직관적인 이름으로 수정 및 node 에서 발생하는 warning 해결
  src/components/common/Comment/Comment.jsx
  src/components/common/Modal/ChatRoomModal/ChatRoomModal.jsx
  src/components/common/Modal/CommentModal/CommentModal.jsx
  src/pages/ChatPage/ChatListPage/ChatList.jsx
  src/pages/ChatPage/ChatListPage/ChatListPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
  src/pages/ChatPage/ChatRoomPage/ChatUploadComment.jsx
  src/pages/PostPage/PostUploadPage/ImageUploadButton.jsx
  src/pages/PostPage/PostUploadPage/PostUploadDetail.jsx
Labels: bug fix, cleanup

#452 fix: ProfilePost 앨범뷰 키 중복 경고 해결 (#451)
  src/pages/ProfilePage/ProfilePost/ProfilePost.jsx
Labels: bug fix

#450 fix: 채팅방 삭제 버튼 모달이 정상적으로 작동하지 않는 버그 수정
  src/components/common/Modal/ChatRoomModal/ChatRoomModal.jsx
  src/components/common/TopNavBar/TopTitleNav.jsx
  src/pages/ChatPage/ChatRoomPage/ChatRoomPage.jsx
Labels: feat, bug fix

#456 fix: 특정 input 창에 공백 입력이 가능한 현상 (#445)
  src/pages/JoinPage/ProfileSettingsPage/InputIntro.jsx
  src/pages/JoinPage/ProfileSettingsPage/InputUserName.jsx
  src/pages/ProductPage/ProductRegistrationPage/ItemNameInput.jsx
Labels: bug fix

#459 refactor: 간헐적으로 상품 수정 시 판매 중인 상품에 바로 반영이 안 되는 현상 수정 및 고용량 이미지 업로드 과정에서 발생하는 소요 시간에 대한 UX 개선 (#457, #458)
  src/pages/ProductPage/ProductModificationPage/ProductModificationPage.jsx
  src/pages/ProductPage/ProductRegistrationPage/ProductRegistrationPage.jsx
Labels: bug fix, refactor

#460 feat: feed페이지 탑버튼 추가 (#436)
  src/components/common/Button/TopButton.jsx
  src/pages/FeedPage/FeedPage.jsx
Labels: feat

#462 fix: 이미지 미리 보기 로딩 중에도 버튼이 활성화되는 현상 수정 (#461)
  src/pages/ProductPage/ProductRegistrationPage/ProductRegistrationPage.jsx
Labels: bug fix
